export type PageTemplate =
	| 'blank'
	| 'grid'
	| 'grid-small'
	| 'grid-large'
	| 'dotted'
	| 'dotted-small'
	| 'dotted-large'
	| 'lined'
	| 'lined-small'
	| 'lined-large'
	| 'numbered'
	| 'numbered-small'
	| 'numbered-large'
	| 'todo'
	| 'todo-small'
	| 'todo-large'
	| 'tasklist-progress'
	| 'calendar-year'
	| 'calendar-quarter'
	| 'calendar-month'
	| 'calendar-month-with-notes'
	| 'goals-quarter'
	| 'overview-quarter'
	| 'agenda-day'
	| 'agenda-day-executive'
	| 'agenda-day-timebox'
	| 'agenda-day-mindful'
	| 'agenda-day-split'
	| 'agenda-week'
	| 'notes-year'
	| 'notes-quarter'
	| 'agenda-week-notes'
	| 'agenda-week-notes-columns'
	| 'agenda-week-notes-rows'
	| 'notes-day'
	| 'habit-year-by-week'
	| 'habit-year-by-month'
	| 'finance-tracker'
	| 'meeting-minutes'
	| 'workout-log'
	| 'meal-planner'
	| 'sprint-planner'
	| 'sprint-planner-2-week'
	| 'sprint-planner-3-week'
	| 'sprint-planner-4-week'
	| 'tarot-draw'
	| 'natal-chart'
	| 'eisenhower-matrix'
	| 'garden-planner'
	| 'project-planner'
	| 'content-planner'
	| 'assignment-tracker'
	| 'wellness-journal'
	| 'learning-tracker'
	| 'energy-matrix'
	| 'client-tracker'
	| 'side-quest-tracker'
	| 'okr-tracker'
	| 'pomodoro-tracker'
	| 'event-planner'
	| 'travel-planner'
	| 'recipe-card'
	| 'reading-log'
	| 'media-tracker'
	| 'pet-care'
	| 'language-learning'
	| 'chore-chart'
	| 'stoic-reflection'
	| 'session-log'
	| 'lesson-plan'
	| 'grade-tracker'
	| 'property-listing'
	| 'character-sheet'
	| 'word-count-tracker'
	| 'meditation-log'
	| 'devotional-page'
	| 'gratitude-page'
	| 'future-log-year'
	| 'agenda-week-split'
	| 'agenda-biweek'
	| 'agenda-week-timebox'
	| 'agenda-day-high-performance'
	| 'agenda-week-focus'
	| 'collection-index'
	| 'cover';

export interface Collection {
	id: string;
	name: string;
	type: PageTemplate;
	total: number;
	columns?: number;
	indexColumns?: number;
	lines?: number;
	numIndexPages?: number;
	numPagesPerItem?: number;
}

export interface TemplateCategory {
	id: string;
	title: string;
	icon: string;
	description: string;
	prefixes: string[];
}
